"""Actualizacion de Modelo

Revision ID: 1fbb352ac525
Revises: 
Create Date: 2024-02-29 17:32:13.968937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fbb352ac525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doc_Type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_doc_name', sa.String(length=50), nullable=False),
    sa.Column('type_doc_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('doc_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=True))
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Doc_Type', ['doc_type_id'], ['id'])
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_ibfk_1', 'doc_type', ['doc_type_id'], ['id'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('doc_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_doc_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type_doc_description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Doc_Type')
    # ### end Alembic commands ###
